name: Java CI with Gradle
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
permissions:
  contents: read
jobs:
  build_voldeloom:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.3.2', '1.4.7', '1.5.2', '1.6.4' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          build-root-directory: ./h-voldeloom-${{matrix.version}}
          arguments: build
          cache-disabled: true
  build_retrofuturagradle:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.7.10', '1.12.2' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          build-root-directory: ./h-retrofuturagradle-${{matrix.version}}
          arguments: build
          cache-disabled: true
  build_forgegradle_legacy:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.8.9', '1.9.4', '1.10.2', '1.11.2' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 8
        uses: actions/setup-java@main
        with:
          java-version: '8'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          build-root-directory: ./h-forgegradle-${{matrix.version}}
          arguments: build
          cache-disabled: true
  build_forgegradle:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.13.2', '1.14.4', '1.15.2', '1.16.5', '1.17.1', '1.18.2', '1.19.4', '1.20.6' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          build-root-directory: ./h-forgegradle-${{matrix.version}}
          arguments: build
          cache-disabled: true
  build_fabric:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.14.4', '1.15.2', '1.16.5', '1.17.1', '1.18.2', '1.19.4', '1.20.6' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          build-root-directory: ./h-fabric-${{matrix.version}}
          arguments: build
          cache-disabled: true
  build_neoforge:
    runs-on: windows-latest
    strategy:
      matrix:
        version: [ '1.20.6' ]
    steps:
      - uses: actions/checkout@main
      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          distribution: temurin
      - name: Build with Gradle
        uses: gradle/gradle-build-action@main
        with:
          build-root-directory: ./h-neoforge-${{matrix.version}}
          arguments: build
          cache-disabled: true
